exoscale/egoscale

src/egoscale/keypair.go
src/egoscale/types.go

Add DeleteSSHKeyPair, by request from @vincentbernat

keypair: add deletesshkeypair

---

.travis.yml
README.md
request.go

- golint needs some documentation work before being o.k.
- also... it would be lovely to have some tests.

Enable travis (gofmt + vet)

---

.travis.yml
topology.go
topology_test.go

It enables using the full name of the Image, as displayed in Portal or fetched from cs.

Test topology

---

topology.go
topology_test.go

https://github.com/exoscale/docker-machine/blob/master/drivers/exoscale/exoscale.go#L311-L321
also line 181, meh...

fix: docker-machine driver expects lowercase strings

---

affinitygroup.go
async.go
error.go
groups.go
ip.go
ip_test.go
request.go
responses.go
topology.go
topology_test.go
types.go
vm.go

Add support to create/destroy EIP.
- https://community.exoscale.ch/api/compute/#associateipaddress_GET
- https://cloudstack.apache.org/api/apidocs-4.9/apis/associateIpAddress.html

Associate IP (wip)

---

affinitygroup.go
groups.go
ip.go
ip_test.go
nic.go
request.go
responses.go
topology.go
types.go
vm.go

documentation + ip

---

types.go
vm.go

Add support for a custom rootdisksize

---

responses.go
types.go
volume.go

volumes: add volumes

---

networks.go
networks_test.go
virtual_machines.go

http://cloudstack.apache.org/api/apidocs-4.4/TOC_User.html

networks: createNetwork is a sync call

---

networks.go

networks: name/displaytext might be empty too

---

README.md

readme: add goreport badge

---

nics.go
virtual_machines.go
virtual_machines_test.go

- `VirtualMachine.DefaultNic()` helper
- more tests

vm: add DefaultNic helper

---

request.go
request_test.go

request: add missing BooleanRequestWithContext

---

request.go
request_test.go

request: test failing sig

---

CHANGELOG.md
nics.go
nics_test.go
virtual_machines.go

vm: add ip4/ip6 flags and linked API call

---

virtual_machines.go
virtual_machines_test.go

virtual machine: test getvmpassword

---

serialization.go
serialization_test.go

#51 got lost in a wild merge...

serialization: proper serialization of *bool

---

addresses.go
addresses_test.go
addresses_type.go
virtual_machines_test.go

address: generic get

---

volumes.go

volume: missing pagesize

---

CHANGELOG.md
security_groups.go
security_groups_test.go

security group: fill startport when zero

---

.travis.yml

travis: fix dep ensure

---

CHANGELOG.md
keypairs.go
keypairs_test.go

make @pierre-emmanuelJ's live easier

keypairs: implements Listable

---

templates.go
templates_test.go
templates_type.go

Template listable

---

addresses.go
addresses_test.go
keypairs.go
nics.go
nics_test.go
templates.go
templates_test.go
virtual_machines.go
volumes.go
volumes_test.go
zones.go
zones_test.go

replace ListCommand implementations with pointers

---

CHANGELOG.md
addresses.go
keypairs.go
templates.go
virtual_machines.go
volumes.go
zones.go
zones_test.go

type assertions are good... we shall use them.
PS: it is expected that the code coverage goes down...

listcommand: check type assertions

---

zones.go
zones_test.go

so, some code can be removed from the TF provider.
https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/provider.go#L206-L221

zones: implements Gettable

---

security_groups.go
security_groups_test.go
security_groups_type.go

security group: make listable

---

addresses_test.go
affinity_groups_test.go
client_test.go
keypairs_test.go
virtual_machines_test.go

client: test generic Delete

---

CHANGELOG.md
zones_type.go

zones: fix and doc

---

addresses_test.go
keypairs_test.go
networks_test.go
templates_test.go
virtual_machines_test.go
volumes_test.go
zones_test.go

Code coverage: add tests 

---

CHANGELOG.md
async_jobs.go
async_jobs_type.go
generate/main.go

async: add doc

---

client_type.go
tags.go
tags_type.go

tags: add doc

---

request.go

So one could produce the HTTP request for debugging purposes (used by the cli branch #33)

request: separate the build of the payload for debug purposes

---

security_groups.go

Fix icmp verification

---

security_groups.go
security_groups_test.go

security group: Add helper

---

apis.go
apis_type.go
generate/README.md
generate/main.go
resource_metadata.go
resource_metadata_test.go
resource_metadata_type.go
tags_type.go
users.go
users_test.go
users_type.go

More commands
- `listResourceDetails`
- `createUser`, `updateUser`, `listUsers`

Missing commands

---

generate/main.go
network_offerings.go
network_offerings_test.go
network_offerings_type.go
networks.go
networks_test.go
networks_type.go
request.go
request_test.go
serialization_test.go
service_offerings.go
service_offerings_type.go
users_type.go

and some fixes too.
for @marcaurele 
- https://github.com/apache/cloudstack/pull/2596
- https://github.com/apache/cloudstack/pull/2597

networks: add documentation

---

CHANGELOG.md
generate/main.go
virtual_machines.go
virtual_machines_test.go
virtual_machines_type.go

Add `getVirtualMachineUserData` call, and document the rest.

get VM UserData

---

virtual_machines_test.go
virtual_machines_type.go

vms: remove ostypeid (untile it because a UUID)

---

CHANGELOG.md
addresses_test.go
affinity_groups_test.go
async_jobs.go
client_type.go
doc.go
networks_test.go
request.go
request_test.go
request_type.go
security_groups_test.go
snapshots_test.go
tags_test.go

Add AsyncRequest

---

generate/main.go
security_groups_type.go

sg: add documentation

---

addresses.go
addresses_type.go
generate/main.go

addresses: add documentation

---

addresses_type.go
request.go
request_type.go
security_groups_type.go
snapshots_type.go
volumes_type.go

global: remove jobid jobstatus from tasks

---

nics_type.go

nics: add documentation

---

events.go
generate/main.go

event types: add documentation

---

generate/main.go
virtual_machines_type.go
volumes_type.go

volumes: add documentation

---

generate/main.go
virtual_machines.go
virtual_machines_test.go
virtual_machines_type.go

vm: add migrateVirtualMachine

---

generate/main.go
templates.go
templates_test.go
templates_type.go

I'm really unsure about how `extractTemplate` is supposed to work, do we need it?

Doc template

---

client_test.go
service_offerings.go
service_offerings_test.go
service_offerings_type.go

Add serviceOffering gettable

---

CHANGELOG.md
virtual_machines.go
virtual_machines_type.go

there are not good releases without a bugfix 30min after that.

Fix userdata

---

client.go
init_test.go

Fibonacci is nerdy and doesn't play well with the patience of a real human... the egoscale cli is deceiving because of that.

client: waiting two seconds by default, always

---

Gopkg.lock
Gopkg.toml
Jenkinsfile
Makefile
cmd/cs/Gopkg.lock
cmd/cs/Gopkg.toml
cmd/cs/Makefile

@pierre-emmanuelJ this should help with the exo integration

deps: untangle Gopkg mess

---

Gopkg.toml
cmd/exo/Gopkg.lock
cmd/exo/Gopkg.toml
cmd/exo/cmd/config.go
cmd/exo/cmd/root.go
cmd/exo/cmd/serviceoffering.go
cmd/exo/cmd/template.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/zone.go

Fix path creation

---

.goreleaser.yml
.travis.yml

gorelease: use skip-sign within travis

---

request.go
request_test.go

Fix error on content-type response

---

request_test.go

Add test on body response

---

addresses.go
affinity_groups.go
client.go
client_test.go
client_type.go
keypairs.go
service_offerings.go
templates.go
virtual_machines.go
volumes.go
zones.go

Add payload on Get and List

---

cmd/exo/cmd/vm_delete.go

Perform vm delete

---

.gitignore
.goreleaser.yml
.travis.yml
cmd/cs/printjson.go

goreleaser: deb, rpm

---

CHANGELOG.md
cmd/cs/layout.go
users.go
users_test.go
users_type.go
virtual_machines_type.go

users: add deleteUser

---

.travis.yml

travis: separate jobs

---

cmd/cs/gen_doc.go
cmd/cs/main.go
website/prepare.sh

```
+ cp ../README.md content/_index.md
+ cp ../cmd/cs/README.md content/cs/_index.md
+ cp ../cmd/exo/README.md content/cli/_index.md
+ mkdir -p static
+ cp ../gopher.png static
+ cd ../
+ dep ensure -vendor-only
+ cd cmd/cs
+ dep ensure -vendor-only
+ go build
+ ./cs gen-doc
create file: ../../website/content/cs/createSnapshot.md
create file: ../../website/content/cs/deleteSnapshot.md
create file: ../../website/content/cs/listSnapshots.md
create file: ../../website/content/cs/revertSnapshot.md
create file: ../../website/content/cs/activateIp6.md
create file: ../../website/content/cs/addIpToNic.md
create file: ../../website/content/cs/listNics.md
create file: ../../website/content/cs/removeIpFromNic.md
create file: ../../website/content/cs/enableAccount.md
create file: …
```

cs: gen-doc to not complain if config is missing

---

cmd/exo/cmd/config.go
cmd/exo/cmd/root.go

Remove double call to config when first run

---

cmd/exo/doc/main.go

Add usage string on none runable command

---

cmd/exo/cmd/firewall_add.go

https://github.com/exoscale/egoscale/issues/186

Exo: firewall add X http https

---

cmd/cs/layout.go
generate/main.go
hosts.go
virtual_machines.go

Port to master the issues fixed there: #191

Backport pcidevices

---

cmd/exo/cmd/vm_delete.go
cmd/exo/main.go

exo vm delete (--force)

---

cmd/exo/cmd/affinitygroup_create.go
cmd/exo/cmd/affinitygroup_delete.go
cmd/exo/cmd/affinitygroup_list.go
cmd/exo/cmd/config.go
cmd/exo/cmd/config_delete.go
cmd/exo/cmd/config_list.go
cmd/exo/cmd/config_set.go
cmd/exo/cmd/config_show.go
cmd/exo/cmd/eip_create.go
cmd/exo/cmd/eip_delete.go
cmd/exo/cmd/eip_list.go
cmd/exo/cmd/firewall_delete.go
cmd/exo/cmd/firewall_list.go
cmd/exo/cmd/firewall_remove.go
cmd/exo/cmd/privnet_create.go
cmd/exo/cmd/privnet_delete.go
cmd/exo/cmd/privnet_list.go
cmd/exo/cmd/root.go
cmd/exo/cmd/ssh.go
cmd/exo/cmd/sshkey_create.go
cmd/exo/cmd/sshkey_delete.go
cmd/exo/cmd/sshkey_list.go
cmd/exo/cmd/sshkey_upload.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/vm_delete.go
cmd/exo/cmd/vm_list.go
cmd/exo/cmd/vm_show.go

exo: Add alias

---

cmd/exo/cmd/template.go
cmd/exo/cmd/template_list.go

https://github.com/exoscale/egoscale/issues/205

Add template keywords filter

---

cmd/exo/cmd/privnet_create.go
networks.go

Refacto and add default zone on privnet

---

cmd/exo/cmd/eip.go
cmd/exo/cmd/eip_associate.go
cmd/exo/cmd/eip_dissociate.go
cmd/exo/cmd/eip_list.go
cmd/exo/cmd/eip_show.go
cmd/exo/cmd/root.go

exo: Add dissociate eip command

---

cmd/cs/gen_doc.go
website/prepare.sh

less noise... http://exoscale.github.io/egoscale/cs/listapis/

website: show only visible cs flags

---

cmd/exo/cmd/privnet.go
cmd/exo/cmd/privnet_associate.go
cmd/exo/cmd/privnet_delete.go
cmd/exo/cmd/privnet_dissociate.go
cmd/exo/cmd/privnet_list.go
cmd/exo/cmd/privnet_show.go
cmd/exo/cmd/vm_create.go

implem privnet associate, dissociate, show

---

cmd/exo/cmd/ssh.go
cmd/exo/cmd/template.go
cmd/exo/cmd/template_list.go

```console
% exo ssh louie --infos
Virtual machine name louie with ID 2c506c8e-dad4-44ef-a18c-365670ed265a                                                                      
- sshkey path: /home/yoan/.exoscale/instances/2c506c8e-dad4-44ef-a18c-365670ed265a/id_rsa                                                   
- username@IPadress: ubuntu@89.145.163.3
```
```console
% exo ssh louie --infos
Host louie
HostName 89.145.163.3
User ubuntu
IdentityFile /home/yoan/.exoscale/instances/2c506c8e-dad4-44ef-a18c-365670ed265a/id_rsa 
```

exo: ssh info to be like .ssh/config

---

Jenkinsfile
cmd/exo/cmd/affinitygroup.go
cmd/exo/cmd/config.go
cmd/exo/cmd/config_delete.go
cmd/exo/cmd/config_list.go
cmd/exo/cmd/config_set.go
cmd/exo/cmd/config_show.go
cmd/exo/cmd/eip.go
cmd/exo/cmd/eip_associate.go
cmd/exo/cmd/eip_dissociate.go
cmd/exo/cmd/firewall.go
cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_remove.go
cmd/exo/cmd/privnet.go
cmd/exo/cmd/serviceoffering.go
cmd/exo/cmd/ssh.go
cmd/exo/cmd/sshkey_create.go
cmd/exo/cmd/template.go
cmd/exo/cmd/vm.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/zone.go

jenkins: make golint work again

---

cmd/exo/cmd/firewall_remove.go

fixes #219 
```
% exo firewall remove my-cluster --all
[+] Are you sure you want to delete all 4 firewall rule(s) from my-cluster [yN]: y
2703d859-dad8-4af4-8d68-21331cb9c5ed
1b41d980-da10-435b-8ea7-34d88d8875f9
575c2ff7-0160-418b-ad6d-1457bb2e082d
9724d051-ad7d-4dbd-b210-7c45c33d7d9a
```

exo: firewall remove all counter

---

cmd/exo/cmd/root.go
version.go

```console
% exo version
exo version 0.10.1-SNAPSHOT
```

exo: add version command

---

cmd/exo/cmd/firewall.go
cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_delete.go
cmd/exo/cmd/firewall_list.go
cmd/exo/cmd/firewall_remove.go
cmd/exo/cmd/firewall_show.go
cmd/exo/cmd/flags.go
cmd/exo/cmd/vm_create.go
cmd/exo/table/table.go
security_groups.go
security_groups_test.go

closes #221 
% exo firewall create my-cluster
|    NAME    |                  ID                  |
|------------|--------------------------------------|
| my-cluster | 2a905059-2593-4705-9a77-3c6f3d0845af |
% exo firewall list
|    NAME    |      DESCRIPTION       |                  ID                  |
|------------|------------------------|--------------------------------------|
| my-cluster |                        | 2a905059-2593-4705-9a77-3c6f3d0845af |
| default    | Default Security Group | 04863b8b-fe3a-45c6-8208-46dc245425a6 |
% exo firewall list default
|  NAME   |      DESCRIPTION       |                  ID                  |
|---------|------------------------|--------------------------------------|
| default | Default Security Group | 04863b8b-fe3a-45c6-8208-46dc245425a6 | …

exo firewall separate show and list

---

cmd/cs/gen_doc.go

cs: simpler formatting for the website

---

cmd/exo/cmd/root.go
cmd/exo/cmd/template.go

Add global ctx

---

cmd/exo/cmd/ssh.go

Add warning on sshkey

---

cmd/exo/cmd/vm_create.go

#224 
```
$ exo vm create test
Creating sshkey
Deploying "test"..........
The deployment of "test" went well! What to do now?
Connect to the machine
> exo ssh test --print
ssh -i ~/.exoscale/instances/.../id_rsa ubuntu@159.100.244.116
Put the SSH configuration into ".ssh/config"
> exo ssh test --info
Host test
HostName 159.100.244.116
User ubuntu
IdentityFile /Users/jacqui_p/.exoscale/instances/.../id_rsa
Tip of the day: you're the sole owner of the private key. Be cautious with it.
```

Add ssh connection detail

---

cmd/exo/cmd/vm_create.go
cmd/exo/cmd/vm_delete.go

exo vm: create/delete outputs

---

cmd/exo/cmd/config.go

closes #236 
```console
% exo config       
Good day! exo is already configured with accounts:
- cloudstack-testing [Default]
[+] Do you wish to add another account? [yN]: ^C^C^C^C^C^C^C^CEOF
%
```
```console
% exo config
Good day! exo is already configured with accounts:
- cloudstack-testing [Default]
[+] Do you wish to add another account? [yN]: ^C
%
```

config: read to use context.Done

---

cmd/cs/flags.go

cs: fix uint8 and uint16 flags

---

client.go
client_test.go

client: prevent panic

---

generate/main.go

generate: style fixes

---

cidr.go
cidr_test.go
cmd/cs/flags.go
cmd/cs/main.go
cmd/exo/cmd/firewall.go
cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_remove.go
networks.go
nics.go
security_groups.go
serialization.go
serialization_test.go

cidr: be picky with cidr

---

cmd/exo/cmd/sshkey.go
cmd/exo/cmd/sshkey_create.go
cmd/exo/cmd/sshkey_delete.go
cmd/exo/cmd/sshkey_list.go
cmd/exo/cmd/sshkey_upload.go

It lets you filter when using `exo sshkey ls`

exo sshkey: use gContext everywhere

---

cmd/exo/cmd/vm_reboot.go

implem exo vm reboot

---

cmd/exo/cmd/serviceoffering.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/vm_scale.go

implem exo vm scale

---

cmd/exo/cmd/vm_resize.go

normal e.g
```
$ exo vm resize toto --disk 200
[+] sure you want to resize "toto" virtual machine [yN]: y
Resizing "toto" ... success.
```
force e.g
```
$ exo vm resize toto --disk 200 -f
Resizing "toto" .. success.
```

Implem exo vm resize

---

cmd/exo/cmd/flags.go
cmd/exo/cmd/vm_reset.go
request.go

Implem exo vm reset (restore)

---

cmd/exo/cmd/config.go
cmd/exo/cmd/config_show.go
cmd/exo/cmd/root.go
cmd/exo/cmd/vm_create.go

Set default template implicitly by default

Add default template

---

.gometalinter.json
addresses.go
async_jobs.go
cmd/exo/cmd/privnet.go
cmd/exo/cmd/template.go
cmd/exo/doc/main.go
cmd/exo/table/table.go
doc.go
generate/main.go
network_offerings.go

Enable misspell

---

cmd/exo/Gopkg.lock
cmd/exo/Gopkg.toml
cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_remove.go
cmd/exo/cmd/request.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/vm_delete.go

exo: Add async tasks progress bar

---

cidr.go
cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_remove.go

Implem #282

---

apis.go
generate/main.go

apis: enable recursive response structs

---

serialization.go
serialization_test.go

serialization: []UUID weren't properly serialized

---

request.go

since we will fix the source of the error.

request: try good response name first

---

.travis.yml
Gopkg.lock
cmd/cs/Gopkg.lock
cmd/exo/Gopkg.lock

the `.lock` file format changed.

travis: check that dep is o.k.

---

cmd/exo/cmd/firewall_add.go
cmd/exo/cmd/firewall_remove.go
cmd/exo/cmd/request.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/vm_delete.go

destroy vm reply example
```Golang
vms := allvm // example
resps := asyncTasks(tasks)
for i, r := range resps {
vm := vms[i]
if r.error != nil {
fmt.Fprintf(os.Stderr, "virtual machine %q error: %s\n", vm.Name, r.error.Error()) // nolint: errcheck
continue
}
folder := path.Join(gConfigFolder, "instances", vm.ID.String())
if _, err := os.Stat(folder); !os.IsNotExist(err) {
if err := os.RemoveAll(folder); err != nil {
return err
}
}
}
```

Improve async response and perform vm delete async

---

apis.go
async_jobs.go
client.go
client_test.go
request.go

client: higher code coverage (even fake)

---

CHANGELOG.md
generate/main.go
virtual_machines.go
virtual_machines_test.go

reflects the new call `updatevmNicIp` which has yet to be merged into community.
https://github.com/exoscale/community/pull/105

Update vm nic ip

---

security_groups.go
security_groups_test.go

https://github.com/exoscale/terraform-provider-exoscale/issues/179

security group: remove tags

---

networks.go

https://community.exoscale.com/api/compute/#updatenetwork_GET

updateNetwork: add missing startip, endip, netmask

---

CHANGELOG.md
virtual_machines.go

Vm is moving

---

cmd/cs/layout.go
cmd/exo/cmd/api_layout.go

Reflect the community changes.
https://community.exoscale.com/api/compute/#updatevmnicip_GET

exo: expose updateVmNicIp in the cli

---

CHANGELOG.md
client_test.go
network_offerings.go

This makes the  `exo privnet` commands potentially simpler.

Listable network offering

---

cmd/exo/cmd/privnet.go
cmd/exo/cmd/privnet_associate.go
cmd/exo/cmd/privnet_show.go

```
exo privnet show da9b7b1b-8906-4e0d-9f42-09a985044f02
┼──────────┼──────┼─────────────────────────┼─────────────────────────────────────────┼──────────────────────────────────────┼
│   ZONE   │ NAME │          DHCP           │             VIRTUAL MACHINE             │          VIRTUAL MACHINE ID          │
┼──────────┼──────┼─────────────────────────┼─────────────────────────────────────────┼──────────────────────────────────────┼
│ ch-gva-2 │ foo  │ 11.0.0.1-11.0.0.200 /24 │ bar                                     │ afdff495-1be3-4977-bf60-2ec980568a3d │
│          │      │                         │ VM-f466061e-a584-4a90-bb8c-88e3fe4b4097 │ f466061e-a584-4a90-bb8c-88e3fe4b4097 │
┼──────────┼──────┼─────────────────────────┼─────────────────────────────────────────┼──────────────────── …
```

privnet show: show DHCP informations in the command output

---

cmd/exo/cmd/privnet_update.go

This call can be used to update an existing private network.

privnet: updateNetwork call

---

README.md

A nice way to help people knowing how it's being used.

readme: more links

---

cmd/cs/layout.go

cs: add missing vm-group calls

---

CHANGELOG.md
client_test.go
nics.go
nics_test.go

listNics doesn't need a virtualmachineid anymore.

New listnics

---

security_groups.go
virtual_machines.go

- ingress/egress IPIP protocol
- tags in the security groups

structs: update w.r.t. the apis changes

---

doc.go

doc: less cloudstack

---

generate/main.go

when running generate/main.go, the errors were shuffled differently each time... not super useful.

generate: order the error messages

---

virtual_machines.go

Making @falzm live easier.
used there: https://github.com/exoscale/cli/pull/74

virtual machine: list using tags

---

CHANGELOG.md
client_test.go
isos.go
isos_response.go
isos_test.go
templates.go

Closes #376 
**Q:** Should we use `Iso` (Usual CloudStack) or `ISO` (like the resource name)? `attacheIso` vs `attachISO`

isos: add the calls

---

CHANGELOG.md
uuid.go
uuid_test.go

uuid: implements DeepCopy on UUID

---

.golangci.yml
.travis.yml
generate/main.go
uuid.go

lint: add scopelint

---

CHANGELOG.md
dns.go

dns: add context

---

.travis.yml

travis: add go1.12

---

CHANGELOG.md
virtual_machines.go

Needed by https://github.com/exoscale/cli/pull/105

vm: IDs to be UUIDs

---

CHANGELOG.md
affinity_groups.go

affinity group: list virtual machines with UUIDs

---

dns.go

dns: user_id is not sent back

---

README.md

readme: point to new lego org

---

addresses.go

- Add healthcheck parameters in UpdateIPAddress
- Remove the unused CustomID parameter

addresses: Add healthcheck parameters in UpdateIPAddress

---

templates.go

Custom templates should not be featured

RegisterCustomTemplate: remove the isFeatured parameters

---

async_jobs.go
async_jobs_test.go

Add this two methodes for using them in the cluster-api exoscale
cf: https://github.com/exoscale/egoscale/pull/385

Add deepCopy on AsyncJobResult

---

.golangci.yml
cidr_test.go
macaddress_test.go
request_test.go

golangci-lint: enable go-critic

---

.travis.yml

was 1.15
the new problems found are fixed by #405

travis: golangci-lint v1.17.1

---

cserrorcode_string.go
errorcode_string.go
jobstatustype_string.go
record_string.go
request_type.go

Go generate: update generation for stringer package to match existing type, that's will fix some bug if stringer type is used

Add 404 errorCode type

---

instance_pool.go

Add `evictInstancePoolMembers` call

Add evictInstancePoolMembers call

---

virtual_machines.go

This change introduces complementary information related to Virtual
Machines's Instance Pool.

Add Instance Pool related info to Virtual Machines

---

client.go

This change fixes a bug where the `User-Agent` header wasn't actually
set in HTTP requests during standard use (i.e. no request tracing enabled).

Fix HTTP request User Agent header handling

---

addresses.go
go.mod

Support for the upcoming new healthcheck options.

healthcheck: support new TLS options

---

addresses.go
go.mod

fix: typos

---

instance_pool.go

This change adds support for IPv6 in Instance Pools.

Instance Pools: add support for IPv6

---

instance_pool.go

This change adds support for Instance Pool root disk size update.

Add support for Instance Pool root disk size update

---

internal/v2/async_test.go
internal/v2/loadbalancer_test.go
internal/v2/v2.gen.go
loadbalancer.go
loadbalancer_test.go

This change adds support for Network Load Balancer service HTTPS health checking.

Add support for NLB service HTTPS health checking

---

instance_pool.go

This change adds support for Anti-Affinity Groups to Instance Pools.

InstancePool: add support for Anti-Affinity Groups

---

sks.go
sks_test.go

This change adds support for Security Groups to SKS Nodepools.

SKS: add support for Security Groups

---

internal/v2/sks_cluster.go
internal/v2/sks_cluster_test.go
internal/v2/sks_nodepool_test.go
internal/v2/v2.gen.go
sks.go
sks_test.go
v2.go

* Add support for `enable-exoscale-cloud-controller` flag
* Test SKS Nodepools Security Groups

Update SKS-related resources

---

internal/v2/v2.gen.go
sks.go
sks_test.go

This change introduces new SKS-related methods.

SKS: add new methods

---

virtual_machines.go
virtual_machines_test.go

in preparation for the upcoming release

virtual_machines: support for new updateVirtualMachineSecurityGroups command

---

v2/security_group.go
v2/security_group_test.go

This change introduces support for Security Groups resources management
via the Exoscale V2 API.

v2: add support for Security Groups management

---

v2/private_network.go
v2/private_network_test.go

This change introduces support for Private Network resources management
via the Exoscale V2 API.

v2: add support for Private Networks management

---

v2/instance_pool.go
v2/instance_pool_test.go
v2/internal/public-api/public-api.go

This change introduces support for Instance Pool resources management
via the Exoscale V2 API.

v2: add support for Instance Pools management

---

v2/instance_pool.go
v2/instance_pool_test.go
v2/sks.go
v2/sks_test.go
v2/v2.go
v2/v2_test.go

This change introduces new v2 methods for public API resource fields
resetting.

v2: add support for field resetting

---

v2/api/middleware.go
v2/client.go

This change introduces an HTTP request tracing middleware, which can be
enabled conditionally using the new `ClientOptCond` client option.

v2: add request tracing middleware

---

v2/elastic_ip.go
v2/elastic_ip_test.go

This change introduces support for Elastic IP resources management
via the Exoscale V2 API.

v2: add support for Elastic IP management

---

v2/elastic_ip_test.go
v2/instance.go
v2/instance_pool_test.go
v2/instance_test.go
v2/internal/public-api/public-api.gen.go
v2/internal/public-api/sks_nodepool.go
v2/internal/public-api/sks_nodepool_test.go
v2/internal/public-api/snapshot.go
v2/sks.go
v2/sks_test.go

* Add `Instance.(At|De)tach*` methods
* Add support for Instance Prefix to SKS Nodepools
* Add support for Deploy Targets to SKS Nodepools

v2: add support for Deploy Target/Instance Prefix to SKS Nodepools

---

v2/anti_affinity_group.go
v2/client.go
v2/client_test.go
v2/elastic_ip.go
v2/instance.go
v2/instance_pool.go
v2/instance_test.go
v2/internal/public-api/async.go
v2/internal/public-api/async_test.go
v2/internal/public-api/loadbalancer.go
v2/internal/public-api/loadbalancer_test.go
v2/internal/public-api/public-api.gen.go
v2/network_load_balancer.go
v2/network_load_balancer_test.go
v2/private_network.go
v2/security_group.go
v2/security_group_test.go
v2/sks.go
v2/snapshot.go
v2/template.go

* v2: refresh code generated from public API spec
* v2: add labels support for Network Load Balancers
* v2: make API async polling interval customizable
* v2: add Start/Stop methods to Instance

v2: API spec refresh & new methods

---

v2/client_test.go
v2/database.go
v2/database_test.go
v2/internal/public-api/dbaas_service.go
v2/internal/public-api/dbaas_service_backup.go
v2/internal/public-api/dbaas_service_backup_test.go
v2/internal/public-api/dbaas_service_test.go
v2/internal/public-api/dbaas_service_user.go
v2/internal/public-api/dbaas_service_user_test.go
v2/internal/public-api/loadbalancer_test.go
v2/internal/public-api/public-api.gen.go
v2/internal/public-api/test.go
v2/network_load_balancer.go
v2/network_load_balancer_test.go

This change introduces support for Database Services resources
management via the Exoscale V2 API.

v2: add support for Database Services management 

---

v2/database_test.go
v2/instance.go
v2/instance_pool_test.go
v2/instance_test.go
v2/internal/public-api/dbaas_service_test.go
v2/internal/public-api/public-api.gen.go
v2/private_network.go
v2/private_network_test.go

* v2: add `Instance.Reboot()` method
* v2: add `PrivateNetwork.UpdateInstanceIPAddress()` method

v2: new methods

---

v2/network_load_balancer.go

This change fixes the required operation parameters validation for NLB
services operations.

v2: fix required params validation for NLB services

---

v2/internal/public-api/sks_nodepool.go
v2/internal/public-api/sks_nodepool_test.go
v2/sks.go
v2/sks_test.go

This change adds support for SKS Nodepool add-ons.

v2: add support for SKS Nodepool add-ons

---

v2/anti_affinity_group.go
v2/elastic_ip.go
v2/instance.go
v2/instance_pool.go
v2/network_load_balancer.go
v2/private_network.go
v2/security_group.go
v2/sks.go
v2/snapshot.go
v2/ssh_key.go
v2/template.go

This change adds missing operation input params validation check.

v2: validate operation params

---

v2/sks_cluster.go
v2/sks_cluster_test.go

This change introduces a new `CreateSKSClusterWithOIDC()` configuration
function for the `CreateSKSCluster()` method.

v2: add support for SKS Cluster OIDC configuration

---

CHANGELOG.md
Makefile
go.mod
v2/oapi/.gitignore
v2/oapi/oapi.gen.go
v2/template.go
v2/template_test.go

<-> https://github.com/exoscale/entities/pull/386

V2: add support for Build, Maintainer and Version attributes to RegisterTemplate

---

v2/elastic_ip.go
v2/elastic_ip_test.go
v2/oapi/oapi.gen.go

This PR adds support for IPV6 Elastic IP in v2 API.

v2: EIPV6 support

---

v2/client_mock.go
v2/elastic_ip.go
v2/elastic_ip_test.go
v2/instance.go
v2/instance_test.go

Added reverse DNS methods for Instance and Elastic IP.

v2: implement reverse DNS endpoints

---

CHANGELOG.md
v2/template.go
v2/template_test.go
version/version.go

```
go test -timeout 30s -testify.m ^(TestClient_GetTemplateByName)$ github.com/exoscale/egoscale/v2
PASS
ok  	github.com/exoscale/egoscale/v2	3.015s
```

template: GetTemplateByName and sorting for []*Template

---

v2/oapi/oapi.gen.go
v2/sks_nodepool_test.go

- update oapi.gen.go
- rename  SKS nodepool addon

v2: Update oapi.gen.go

---

v2/private_network.go
v2/private_network_test.go

Adds Labels (to replace Tags from v1) to private network.

Add private network labels

---

v3/client.go
v3/clientopts.go
v3/zoned_client.go

This PR adds zone-aware wrapper around V3 Client.

Egoscale V3 - Zone wrapper

---

.gitignore
v3/client.go
v3/generator/client/client.go
v3/generator/client/client.tmpl

Add zoned URL to replace standalone zones and useless `Environment`

Egoscale V3: Replace Zone with url endpoints

---

v3/api.go
v3/client.go
v3/generator/client/client.go
v3/generator/client/client.tmpl

More explicit error message on the default validator
V3 alpha development

V3: Add better message on validator

---

v3/generator/operations/operations.go
v3/generator/schemas/schemas.go
v3/operations.go

Add gettable method on listable resources 
fetch by name or ID.
V3 alpha development

V3: Add gettable on listable resources

---

.github/workflows/main.yml
.github/workflows/release.yml
.gitignore
.gitmodules
CHANGELOG.md
Makefile

go.mk: remove submodule and initialize through make

---

CHANGELOG.md
v3/api.go
v3/generator/operations/operations.go
v3/generator/operations/request.tmpl
v3/operations.go
v3/schemas.go

V3: Add the User-Agent header value

---

CHANGELOG.md
v3/generator/schemas/schemas.go
v3/operations.go
v3/schemas.go

Update instance pool definition
```Yaml
put:
tags:
- instance-pool
responses:
'200':
description: '200'
content:
application/json:
schema:
"$ref": "#/components/schemas/operation"
description: ''
parameters:
- in: path
required: true
name: id
schema:
type: string
format: uuid
summary: Update an Instance Pool
requestBody:
required: true
content:
application/json:
schema:
type: object
properties:
anti-affinity-groups:
type: array
items:
"$ref": "#/components/schemas/anti-affinity-group"
uniqueItems: true
nullable: true
description: Instance Pool Anti-affinity Groups
description:
type: string
maxLength: 255
description: Instance Pool description
public-ip-assignment:
"$ref": "#/components/schemas/public-ip-assignment"
description: Assign public IP to Instances
labels:
"$ref": …
```

V3: Remove omitempty on nullable complex types

---

.github/workflows/main.yml

Runs the CI on PR coming from forks.
Fixes #630

fix: runs the CI on PR coming from forks.

---

CHANGELOG.md
Makefile
client_test.go
generate/main.go
request_test.go
v2/staticcheck.conf

```shell
❯ make lint
'/home/sauterp/bin/go' install honnef.co/go/tools/cmd/staticcheck@2023.1.7
'/home/sauterp/go/bin/staticcheck' \
\
./...
```

go.mk: lint with staticcheck

---

.github/workflows/generate_v3.yaml

Add author Exoscale to v3 generate 

GH Action: Add author Exoscale to v3 generate

---

.github/workflows/generate_v3.yaml
CHANGELOG.md
Makefile
v3/README.md
v3/generator/operations/operations.go
v3/operations.go

Return error with wrapped `ErrConflict` on too many entries found in 'Findable request'

v3 generator: Findable return error on too many found

---

.github/workflows/main.yml

Checks the generated code inside PR.

v3: check generated code

---

v3/generator/schemas/schemas.go
v3/generator/source.yaml
v3/schemas.go

Generator: Fix additional properties spec 3.1

---

CHANGELOG.md
go.mod
v3/go.mod
v3/version.go

Prepare release

---

v3/generator/schemas/schemas.go
v3/operations.go
v3/schemas.go

V3 Generator: Fix false additional properties in object
