exoscale/egoscale

src/egoscale/topology.go
src/egoscale/types.go

On 32-bit arch, int is usually like int32 and is too small for some
types. For example, the size in bytes doesn't fit in 32 bits. Change
some types to int64 when it makes sense.

types: use int64 when we expect large integers

---

src/egoscale/topology.go

Do not limite ourselves to Debian/Ubuntu. The following images will be
accepted:
- centos-6.6
- centos-7.1
- coreos-stable-723
- debian-7
- debian-8
- ubuntu-12.04
- ubuntu-14.04
- ubuntu-15.04
- ubuntu-15.10
- openbsd-5.7
- openbsd-5.8
- windows-server-2008-r1
- windows-server-2012
- windows-server-2012-r2

images: add support for all images

---

exo.go
src/egoscale/affinitygroup.go
src/egoscale/async.go
src/egoscale/topology.go
src/egoscale/types.go
src/egoscale/vm.go

* This creates several types to define Affinity Groups (AF).
* It modifies the Topology and Machine Profile types to add AF.
* It adds an `affinitygroup.go` file for create and delete of AF.
* This modifies `vm.go` to set the AF on VM creation.
Note that if no AF are defined in the profile the VM creation will work.
You can pass multiple AF in the profile.
The example `exo.go` has also been modified to start the VM in a default _egoscale_ AF. Which is created if it does not exist.

Add Affinity Group support

---

src/egoscale/topology.go

If another filter value is used to fetch the template list, more than 1
template will match the parameter, resulting in a random version of a
template being picked up. This result currently in breaking docker
deployment randomly for our customers.

Template: pick up on featured templates

---

request.go
types.go
vm.go

Sending large cloud-init  files is easier in POST.

request: use POST

---

addresses.go
addresses_test.go
affinity_groups.go
affinity_groups_test.go
keypairs.go
keypairs_test.go
networks.go
networks_test.go
nics.go
nics_test.go
request.go
security_groups.go
security_groups_test.go
snapshots.go
snapshots_test.go
tags.go
tags_test.go
virtual_machines.go
virtual_machines_test.go

...and better handling of the errors (will be used by TF)
**edit:** in fact, all the sync boolean response do so, e.g. `deleteSSHKeyPair`
> This code is needed because the response field is different for sync and async calls :(
>
> https://github.com/xanzy/go-cloudstack/blob/master/generate/generate.go#L1274

security_groups: deletion returns success as a string

---

addresses.go
doc.go
networks.go
nics.go
request.go
request_test.go
virtual_machines.go
zones.go

`net.IP` safely serializes to json back and forth.
https://play.golang.org/p/lY04V2brMmN
It's not the case for `net.IPMask`, or `net.HardwareAddr`.

global: use net.IP for IP addresses

---

request.go
request_test.go

Details are serialized this way, after all.
> Template details in key/value pairs using format `details[i].keyname=keyvalue`. Example: `details[0].hypervisortoolsversion=xenserver61`
>
> https://github.com/apache/cloudstack/blob/87ef8137534fa798101f65c6691fcf71513ac978/api/src/org/apache/cloudstack/api/command/user/template/CreateTemplateCmd.java#L123
it impacts other calls like UpdateVM

request: fix map serialization

---

virtual_machines.go

It makes the user responsible for base64 and gzipping (or not) its
content

virtual machines: userdata as string

---

CHANGELOG.md
addresses.go
addresses_test.go
networks.go
networks_test.go
security_groups.go
security_groups_test.go
snapshots.go
snapshots_test.go
tags.go
templates.go
templates_test.go
virtual_machines.go
virtual_machines_test.go
volumes.go
volumes_test.go

CreateTags/DeleteTags require a string representing the resource and its value is not trivial. To make one's life easier, it's now in the library.
source of truth: https://github.com/apache/cloudstack/blob/a86160b389057e6f7241f49313c031db0b079a4f/test/integration/component/test_tags.py

global: add Taggable interface for ResourceType

---

request.go
request_test.go

Consider the polling to be instantaneous and wait for a given delay. Drawbacks, the total amount of time is unknown
https://play.golang.org/p/K8oQsB7DN1H
Poll CloudStack at a fixed point in time and no more than the total amount of time given in the first place.
https://play.golang.org/p/Q3jAsk5_ORf

request: improve monotonic polling

---

accounts.go
addresses.go
affinity_groups.go
async_jobs.go
events.go
keypairs.go
limits.go
networks.go
request.go
request_test.go
security_groups.go
service_offerings.go
snapshots.go
tags.go
templates.go
virtual_machines.go
vm_groups.go
volumes.go
zones.go

When the default value of a boolean field is true, it's impossible to send the `false` value.

global: enable *bool to send false omitempty values

---

virtual_machines.go
virtual_machines_test.go

`DeployVM` now requires at least one security group, either by name or id. And one cannot set both affinity group by name and id.

vm: make security/affinity group ids and names mutually exclusive

---

.travis.yml
CHANGELOG.md
addresses_test.go
affinity_groups_test.go
client.go
client_type.go
doc.go
keypairs_test.go
networks_test.go
nics.go
nics_test.go
request_test.go
security_groups_test.go
virtual_machines_test.go
volumes.go
volumes_test.go
zones.go
zones_test.go

In a nutshell
```go
vm := &egoscale.VirtualMachine{ZoneID: ...}
vms, err := client.List(vm)
if err != nil {
panic(err)
}
for _, i := range vms {
vm := i.(egoscale.VirtualMachine)
...
}
```
other calls:
- `ListWithContext(ctx, vm) ([]interface{}, error)`
- `AsyncList(vm) (<-chan interface{}, <-chan error)`
- `AsyncListWithContext(ctx, vm) (<-chan interface{}, <-chan error)`
**TODO**:

client: generic list

---

CHANGELOG.md
async_jobs.go
client.go
client_type.go
nics.go
nics_test.go
request.go
request_test.go
request_type.go
virtual_machines.go
virtual_machines_test.go
virtual_machines_type.go
volumes.go
volumes_test.go
zones.go
zones_test.go
zones_type.go

`Listable.List` contains too much boilerplate, more _interface_ and _closures_ to the rescue.
```go
// current use case
vm := &egoscale.VirtualMachine{ZoneID: 1}
vms, err := client.List(vm)
// before
client.ListWithContext(ctx, vm) -> ([]interface{}, error)
client.AsyncListWithContext(ctx, vm) -> (<-chan interface{}, <-chan error)
vm.List(ctx, client) -> (<-chan interface{}, <-chan error)
client.RequestWithContext(ctx, ListVirtualMachines...) -> (interface{}, error)
... (page 2)
... etc
// now
client.ListWithContext(ctx, vm)
req <- vm.ListRequest()
client.PaginateWithContext(ctx, req) -> ([]interface{}, error)
// new - grab the query, adapt it, run it
req, _ := vm.ListRequest()
req.Details = []string{"stats", "nics"}
client.Paginate(req, func(i interface{}, e error) bool {
if e != nil { …
```

client: refactor List inner logic

---

doc.go

Fix doc.go to use:
fmt.Printf("%s %s\n", api.Name, api.Description)

replace Println with Printf

---

generate/main.go
snapshots.go
snapshots_type.go

`generate` found some missing fields, big win!
- `createSnapshot.name`
- `listSnapshots.ids`

snapshots: fill up the documentation

---

security_groups_type.go

it will probably need some work in the TF provider, but it's for the greater good

security groups: use more specific type rather than generic int

---

dns.go
request.go
request_test.go
version.go

Sends:
- request as GET by default
- User-Agent containing exoscale/egoscale and a version number

request: send user-agent

---

CHANGELOG.md
client.go

It enables doing a richer dry mode on the cli exposing the expected output if the command where run for real. (NB: the signature is redacted on purpose)
```
$ ./cs -d listZones
https://api.exoscale.ch/compute\
?apikey=EXO34771c9dad3d915cf1aa559e\
&command=listZones\
&response=json
{ 
"count": 0,
"zone": null
}
```

client: expose command expected response type

---

addresses.go
addresses_test.go
affinity_groups.go
affinity_groups_test.go
client_test.go
keypairs.go
keypairs_test.go
networks.go
networks_test.go
nics.go
nics_test.go
request.go
request_type.go
security_groups.go
security_groups_test.go
snapshots.go
snapshots_test.go
tags.go
tags_test.go
virtual_machines.go
virtual_machines_test.go
vm_groups.go
vm_groups_test.go

Apply https://github.com/apache/cloudstack/pull/2428
The trick is to marshal into a `json.RawMessage` with the drawback that is, almost, always works...
https://play.golang.org/p/2AAzw9YwFSr

global: unify sync/async responses

---

.gometalinter.json
Gopkg.lock
Jenkinsfile
client.go
client_test.go
cmd/cs/Gopkg.lock
cmd/cs/layout.go
cmd/cs/main.go
dns.go
request.go
serialization.go
virtual_machines.go

Activation of `gometalinter`, mostly: `errcheck`, `megacheck`, `unconvert`
- `maligned` is deactivated because the alphabetical order is useful (for the cli)
- `gocyclo` because of the struct serialization being hairy
cf. https://github.com/exoscale/dockerfiles/pull/9

global: configure and fixes gometalinter issues

---

website/config.toml
website/content/_index.md
website/layouts/index.html

We are now taking liberties with the Cloudstack API, this
adapts our wording to reflect it.

website: avoid confusion

---

cmd/exo/README.md

The path did not have an additional egoscale directory.
The `dep` command would not accept the '-vendor' option.

fix: edits to get the exo cmd working

---

CHANGELOG.md
dns.go

`DNSErrorResponse` should implement the `error` interface directly.

dns: make DNSErrorResponse an error

---

virtual_machines_type.go

**before**
```shell
% cs listVirtualMachines | jq ".virtualmachine[].pcidevices"
json: cannot unmarshal object into Go struct field VirtualMachine.pcidevices of type string
```
**now**
```json
[
{
"pcivendorname": "NVIDIA Corporation",
"pcivendorid": "10de",
"pcidevicename": "GP100GL [Tesla P100 PCIe 16GB]"
}
]
```

vm: correct representation of a PCI device

---

cmd/exo/cmd/firewall.go

One less call.
**before**
```
API error ParamError 431 (ServerAPIException 9999): Unable to execute API command listsecuritygroups due to invalid value. Invalid parameter id value=mycluster due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.
more than one element found: apikey=EXO9f5db99c785d5821b58627d1, command=listSecurityGroups, response=json                                   
Security group not found wrong ID or Name, got  more than one element found: apikey=EXO9f5db99c785d5821b58627d1, command=listSecurityGroups, response=json
```
**after**
```
Security group not found wrong ID or Name, got  more than one element found: apikey=EXO9f5db99c785d5821b58627d1, command=listSecurityGroups, response=json
```

firewall: use is-uuid

---

addresses.go
networks.go
service_offerings.go

Since the values don't have `*`, `ListRequest` should take into account what is the default value on the cloudstack side. This fix should probably be adapted to other types as well.

addresses: list cannot be that magic

---

.travis.yml
CHANGELOG.md
async_jobs.go
cmd/exo/cmd/vm_create.go
request.go
request_test.go

this exposes two methods:
- `SyncRequest`
- `SyncRequestWithContext`
because there was not way to perform a fire and forget on an asynchronous command.
Another change.
```
// was
err := jobResult.Response(virtualMachine)
// now
err := jobResult.Result(virtualMachine)
```
But, I'm unhappy with it. Should it be called `jobResult.Unmarshal(virtualMachine)`, `Load`, `Hydrate` ?

Sync request

---

cidr.go
cidr_test.go
client_test.go
request.go
request_test.go
request_type.go
reversedns.go
reversedns_test.go

```console
% cs -r testing deleteReverseDnsFromPublicIpAddress --id=97160608-65da-4d4b-903d-bb601da7115a                      
{}
```
_now_
```console
% cs deleteReverseDnsFromPublicIpAddress --id=97160608-65da-4d4b-903d-bb601da7115a                                                          
{
"displaytext": "brutas.se deleted from publicipaddressid 97160608-65da-4d4b-903d-bb601da7115a",                                            
"success": true
}
```
svanharmelen's take is nicer than what was done here.
- https://github.com/xanzy/go-cloudstack/pull/98
- https://github.com/xanzy/go-cloudstack/pull/99

Boolean response

---

cmd/exo/cmd/eip_create.go
cmd/exo/cmd/eip_list.go
cmd/exo/cmd/privnet_create.go
cmd/exo/cmd/privnet_list.go
cmd/exo/cmd/template.go
cmd/exo/cmd/template_list.go
cmd/exo/cmd/template_show.go
cmd/exo/cmd/vm_create.go
cmd/exo/cmd/zone.go

- release date for everyone
- `template show` command
**then**
```console
% exo template list
```
|         OPERATING SYSTEM          | DISK |   RELEASE DATE    |                  ID                  |
|-----------------------------------|------|-------------------|--------------------------------------|
| FortiGate 64-bit                  | 10   |                   | e84ba6e1-1855-4941-965e-22e00cc43d4e |
| Linux CentOS 7.5 64-bit           |      | 2018-06-06-988151 | f4b895cf-caf7-4455-8e6f-ca3632cb1062 |
| Linux CentOS 7.4 64-bit           |      | 2018-01-08-d617dd | 934b8d48-d82e-42f5-8f14-b34de3af9854 |
| Linux CentOS 6.9 64-bit           |      | 2018-01-08-8856b8 | e1db5519-2055-4b67-91ba-d66550e43b68 |
| Linux Centos Atomic Host 7 64-bit |      |                   | …

exo template show

---

.goreleaser.yml

To avoid this message if egoscale was installed through its `deb` package:
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 50951 package 'egoscale':
missing maintainer
```

goreleaser: add maintainer field to make `dpkg` stop complaining

---

cmd/cs/main.go

```console
% cs listAccounts id 12               
unexpected extra arguments found: id 12
% cs listAccounts --id 12             
API error ParamError 431 (InvalidParameterValueException 4350): Unable to find account by id 12
```

cs: fail on extra args

---

dns.go

**now**
```console
% EXOSCALE_TRACE= ./exo dns add CNAME example.exo -n mx -a ""
2018/08/03 15:17:51 POST /dns/v1/domains/example.exo/records HTTP/1.1
Host: ppapi.exoscale.ch
Accept: application/json
Content-Type: application/json
User-Agent: exoscale/egoscale (0.11.0a0)
{"record":{"domain_id":391861,"name":"mx","ttl":3600,"content":"","record_type":"CNAME"}}
2018/08/03 15:17:52 HTTP/2.0 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Fri, 03 Aug 2018 13:17:51 GMT
Strict-Transport-Security: max-age=0; includeSubDomains
X-Request-Id: bdb7c70f-28eb-4fbd-96f6-37e8a60a4cab
{"message":"Validation failed","errors":{"content":["can't be blank"]}}
dns error: Validation failed (content: can't be blank)
```
**before**
```
dns error: Validation failed ()
```

dns: better error messages

---

client.go
cmd/exo/cmd/firewall_list.go

“Just keep in mind that if any concrete value has been stored in the
interface, the interface will not be nil”
-- https://golang.org/doc/faq#nil_error

client: unbreak

---

README.md
cmd/exo/README.md

While installing the CLI, I noticed a couple of small touch-ups that could be made to the READMEs

Point to cmd installation instructions from README

---

cmd/cs/flags.go
cmd/cs/main.go

```console
% cs -j createTags --resourceids 3a13ad68-63f5-42ab-abea-ffeee3363c57,f79d03f2-f514-4715-baa8-3a519e0c23a8 --resourcetype UserVM --tags a:b --tags foo:bar,hello:world
```
```json
{
"resourceids": [
"3a13ad68-63f5-42ab-abea-ffeee3363c57",
"f79d03f2-f514-4715-baa8-3a519e0c23a8"
],
"resourcetype": "UserVM",
"tags": [
{
"key": "a",
"value": "b"
},
{
"key": "foo",
"value": "bar"
},
{
"key": "hello",
"value": "world"
}
]
}
```

cs: fix list of uuids

---

cmd/cs/flags.go
cmd/cs/main.go
serialization.go

fix #289 
```console
% cs -d updateVirtualMachine --id='7d3eea64-6324-464b-b399-3083424e33ab
```
```
https://ppapi.exoscale.ch/compute/\
?apikey=EXOc94bc655ff901b7218a5c3cd\
&command=updateVirtualMachine\
&id=7d3eea64-6324-464b-b399-3083424e33ab\
&response=json
```
```json
{
"account": "account (string) - the account associated with the virtual machine",
"accountid": "accountid (string) - the account ID associated with the virtual machine",
"affinitygroup": [
{
"account": "account (string) - the account owning the affinity group",
"description": "description (string) - the description of the affinity group",
"domain": "domain (string) - the domain name of the affinity group",
"domainid": "domainid (string) - the domain ID of the affinity group",
"id": "id (string) - the ID of the affinity …
```

cs: use listApis for the help

---

client.go
request.go
serialization.go

Fix handling of brackets '[]' in parameter values (e.g.in a description field) and 
when a parameter name contains
'[]' and a POST is used (e.g. during a DeployVirtualMachine).
CloudStack only uses a specialized encoding for the signature
calculation. It only query encodes the values of the query arguments
and always use '%20' for whitespaces (no '+'). But for the GET url
and for the POST body, we always have to use the normal
query escaping as standardized.
Signed-off-by: stffabi <stffabi@pm.me>

Fix handling of brackets '[]'

---

client_test.go
request.go

```console
% cs listVirtualMachines
2018/08/29 11:06:29 GET /compute/?apikey=EXOc94bc655ff901b7218a5c3cd&command=listVirtualMachines&response=json&signature=*** HTTP/1.1
Host: ppapi.exoscale.ch
User-Agent: exoscale/egoscale (0.11.1)
2018/08/29 11:06:29 HTTP/2.0 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 29 Aug 2018 09:06:21 GMT
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Request-Id: f77e40a3-4e41-4976-b515-c9bbaf3a4563
{"listvirtualmachinesresponse":{"virtualmachine":[]}}
```
**before**
```
json: cannot unmarshal array into Go value of type egoscale.ListVirtualMachinesResponse
```
**after**
```json
{
"count": 0,
"virtualmachine": []
}
```

Fix empty list result

---

request.go

**then**
```console
% cs -r testing updateVMAffinityGroup --id 1252eddd-9cbf-4f9e-847c-be25de210ccb --affinitygroupnames yoan 
malformed JSON response, "updatevmaffinitygroupresponse" was expected, got "updatevirtualmachineresponse"
```
**now**
```console
% cs -r testing updateVMAffinityGroup --id 1252eddd-9cbf-4f9e-847c-be25de210ccb --affinitygroupnames yoan   
{
"account": "cloudstack-testing",
"affinitygroup": [
{
"account": "cloudstack-testing",
"id": "9f0b3f8b-b331-479a-81d8-6c9c94c2a699",
"name": "yoan"
}
],
"created": "2018-07-11T08:54:56+0200",
"displayname": "obwald-testing-do-not-delete",
"domain": "cloudstack-testing",
"domainid": "2083e04d-500f-48ef-8e3d-bae6805417cd",
"hypervisor": "KVM",
"id": "1252eddd-9cbf-4f9e-847c-be25de210ccb",
"keypair": "jenkins",
"name": …
```

request: update vm affinity group response

---

cmd/exo/cmd/request.go

closes #322.
```console
% EXOSCALE_TRACE= ./exo privnet update --id 5ee3d97f-3187-4451-8e02-464da7e5c50c --startip=10.0.0.0 --endip=10.0.0.100
2018/09/18 10:40:00 HTTP/2.0 200 OK
Content-Type: application/json; charset=utf-8
Date: Tue, 18 Sep 2018 08:39:38 GMT
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Request-Id: 96c33c94-12e5-491b-b431-3cfcb9a94266
{"updatenetworkresponse":{"jobid":"6125f290-bb1e-11e8-9282-e76b23d3ba0e"}}
{"queryasyncjobresultresponse":{"jobprocstatus":0,"userid":"64024bfa-6de0-40a1-a655-10d16be74d7f","created":"2018-09-18T10:39:38+0200","jobid":"6125f290-bb1e-11e8-9282-e76b23d3ba0e","jobresult":{"errorcode":530,"errortext":"You should provide all of these fields:  start-ip, end-ip, n
etmask."},"jobresultcode":0,"jobstatus":2,"cmd":"org.apache.cloud …
```

exo: failed async job should fail

---

cmd/exo/cmd/affinitygroup.go

the affinity group name wasn't properly set... hence it was failing when one had more than one anti-affinity group (crickey).
**then**
```console
% exo affinitygroup delete my-anti-aff                                                                                      
[+] sure you want to delete "my-anti-aff" affinity group [yN]: y                                                                             
more than one element found: apikey=EXOc94bc655ff901b7218a5c3cd, command=listAffinityGroups, response=json
```
**now**
```console
% exo affinitygroup delete my-anti-aff                                                                                      
[+] sure you want to delete "my-anti-aff" affinity group [yN]: y
7bb25bc3-7901-495e-a5a8-13b578551fb7
```

exo: fix affinity delete

---

cmd/exo/cmd/privnet.go
cmd/exo/cmd/privnet_create.go
cmd/exo/cmd/privnet_list.go
cmd/exo/cmd/privnet_test.go
networks.go

#319 
- Add the `startip`, `endip`, `netmask` parameters to the create
network command
- Show the `startip`, `endip`, `netmask` fields in the list networks command

managed private networks: update the create and list commands

---

client.go
request.go

Enables the API call expiration, 10 minutes by default.
http://docs.cloudstack.apache.org/en/4.11.1.0/developersguide/dev.html?enabling-api-call-expiration

request: signatureVersion=3

---

cmd/exo/cmd/config.go
cmd/exo/cmd/root.go

the config file should use `endpoint` and not `computeEndpoint`, although we forgot to remove some of them. This should fix new config as well as support old ones.
```console
% more ~/.exoscale/exoscale.toml | grep -i endpoint
computeEndpoint = "https://ppapi.exoscale.ch/compute/"
sosEndpoint = "https://ppsos-{zone}.exo.io"
% ./exo api zone ls --keyword de                   
{
"count": 1,
"zone": [
{
"allocationstate": "Enabled",
"dhcpprovider": "VirtualRouter",
"id": "de88c980-78f6-467c-a431-71bcc88e437f",
"localstorageenabled": true,
"name": "de-fra-1",
"networktype": "Basic",
"securitygroupsenabled": true,
"zonetoken": "c4bdb9f2-c28d-36a3-bbc5-f91fc69527e6"
}
]
}
```

exo: config to also pick legacy computeEndpoint

---

serialization.go
serialization_test.go

`net.IPv4zero` serialize as `0.0.0.0` while `net.IP{}` produces `nil`. Only the later should be avoided.

serialization: fail on empty IP, not zero.

---

request.go

Then
```console
% exo api api list
malformed JSON response, "listapisresponse" was expected, got "message"
```
Now
```console
% exo api api list
malformed JSON response 500, "listapisresponse" was expected.
{"message":null}
```
(feel free to ignore the -0.2% code coverage change)

request: show the source message on parsing error.

---

accounts.go
addresses.go
affinity_groups.go
async_jobs.go
events.go
generate/main.go
limits.go
networks.go
nics.go
resource_metadata.go
security_groups.go
snapshots.go
ssh_keypairs.go
tags.go
templates.go
users.go
virtual_machines.go
vm_groups.go
volumes.go

the checking for the return type was disabled when the listApis format changed. This fixes it. Although is doesn't check recursively for sub-struct.
**before**
```console
% go run generate/main.go -apis listApis.json
2 ssh_keypairs.go:76:6: ListSSHKeyPairs
5 virtual_machines.go:264:6: DeployVirtualMachine (A)
2 addresses.go:138:6: ListPublicIPAddresses
2 volumes.go:100:6: ListVolumes
2 networks.go:210:6: ListNetworks
3 accounts.go:85:6: ListAccounts
4 templates.go:76:6: ListTemplates
2 virtual_machines.go:496:6: ListVirtualMachines
4 events.go:24:6: ListEvents
1 service_offerings.go:65:6: ListServiceOfferings
2 resource_metadata.go:4:6: ListResourceDetails
1 ssh_keypairs.go:51:6: DeleteSSHKeyPair
2 ssh_keypairs.go:124:6: ResetSSHKeyForVirtualMachine (A)
1 snapshots.go:58:6: CreateSnapshot …
```

generate: re-enable check of the return type

---

cmd/exo/cmd/privnet_associate.go

`exo privnet associate` can be used to associate a static ip to a private interface:
```
exo privnet associate da9b7b1b-8906-4e0d-9f42-09a985044f02 3c2b2ec6-c7c4-41da-a02f-736a67a93dbd 11.0.0.4 45890f39-9d2a-4d8f-ad78-c18cd32934c9
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│                NIC ID                │          VIRTUAL MACHINE ID          │ IP ADDRESS │
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│ f8464441-0d1e-4c2b-b203-bbe5d1ab55ea │ 3c2b2ec6-c7c4-41da-a02f-736a67a93dbd │ 11.0.0.4   │
│ 2fa5f02a-37b2-439e-b573-987f750452f0 │ 45890f39-9d2a-4d8f-ad78-c18cd32934c9 │ n/a        │
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
```

privnet associate: add an optional ip parameter

---

CHANGELOG.md
virtual_machines.go
virtual_machines_test.go

This call can be used to associate an ip to an existing private
network interface.
The current implementation shows some informations about the updated VM and then the private network interfaces.
```
exo vm updatenicip f8464441-0d1e-4c2b-b203-bbe5d1ab55ea 11.0.0.100
Updating the nic "f8464441-0d1e-4c2b-b203-bbe5d1ab55ea" . success.
Instance ID:           3c2b2ec6-c7c4-41da-a02f-736a67a93dbd
Isntance Hostname:     VM-3c2b2ec6-c7c4-41da-a02f-736a67a93dbd
Instance Display name: test
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│                NIC ID                │              NETWORK ID              │ IP ADDRESS │
┼──────────────────────────────────────┼──────────────────────────────────────┼────────────┼
│ …
```

cli: updateVmNicIp call is async

---

virtual_machines.go

e.g.
```json
{
"pcidevicename": "GP100GL [Tesla P100 PCIe 16GB]",
"pcideviceid": "15f8",
"pcivendorname": "NVIDIA Corporation",
"pcivendorid": "10de"
}
```

vm: pcidevices are not UUID

---

.travis.yml
cidr_test.go
client.go
client_test.go
macaddress_test.go
uuid_test.go

`script: |` vs `script: []` semantics...
it's green but it fails, https://travis-ci.org/exoscale/egoscale/jobs/443563483

travis: tests were failing

---

CHANGELOG.md
client.go
client_test.go

this is suboptimal and we should check that all projects are 1.8+ (I'm looking at you docker/machine)

client: fix authorizeSecurityGroupEgress when non-ptr

---

apis.go

So listApis always display `isasync` even when it's false.

apis: listApis to always show isasync

---

.travis.yml

it feels like the code coverage is fading away, #365 
**TODO** https://docs.codeclimate.com/docs/travis-ci-test-coverage
```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
```

travis: use cc-test-reporter

---

CHANGELOG.md
admin/README.md
admin/doc.go
admin/virtual_machines.go

A minimal usage of this first extended API call. cc @falzm 
```go
package main
import (
"fmt"
"github.com/exoscale/egoscale"
"github.com/exoscale/egoscale/admin"
)
func main() {
cs := egoscale.NewClient("<URL>", "<KEY>", "<SECRET>")
b := true
request := &admin.ListVirtualMachines{
ListVirtualMachines: egoscale.ListVirtualMachines{
ZoneID: egoscale.MustParseUUID("de88c980-78f6-467c-a431-71bcc88e437f"),
},
ListAll: &b,
}
query, _ := cs.Payload(request)
fmt.Println(query.Encode())
}
```
output:
> apikey=%3CKEY%3E&command=listVirtualMachines&expires=2018-11-23T10%3A33%3A43%2B0100&listall=true&response=json&signatureversion=3&zoneid=de88c980-78f6-467c-a431-71bcc88e437f

admin: listVMs for admins

---

CHANGELOG.md
addresses.go
addresses_test.go
affinity_groups.go
affinity_groups_test.go
instance_groups.go
instance_groups_test.go
networks.go
networks_test.go
nics.go
nics_test.go
request.go
request_type.go
reversedns.go
reversedns_test.go
security_groups.go
security_groups_test.go
snapshots.go
snapshots_test.go
ssh_keypairs.go
ssh_keypairs_test.go
tags.go
tags_test.go
virtual_machines.go
virtual_machines_test.go

```console
% sed -i "s/booleanResponse/BooleanResponse/g" *.go
```
cf. https://github.com/exoscale/cli/issues/88

global: export BooleanResponse

---

CHANGELOG.md
affinity_groups.go
affinity_groups_test.go

```console
% cs createAffinityGroup name="" type="host anti-affinity"
{
"affinitygroup": {
"id": "6d06b1e8-f899-4fa9-97ba-1ff202ecc2a4",
"name": "",
"type": "host anti-affinity"
}
}
```

affinity group: empty name should be accepted

---

CHANGELOG.md
runstatus.go
runstatus_incident.go
runstatus_incident_test.go
runstatus_maintenance.go
runstatus_maintenance_test.go
runstatus_page.go
runstatus_page_test.go
runstatus_service.go
runstatus_service_test.go

cf https://github.com/exoscale/cli/pull/84
- `/pages` has an empty maintenances bag, while `/pages/<page>` fills it
- known bug. `/pages/<page>/maintenances` fetches the 50 oldest maintenances
- ditto for incidents and services.

Runstatus maintenance list

---

.gitignore
addresses.go

- Add the Healthcheck field in IPAddress
- Add the healthcheck parameters in the AssociateIPAddress call
Story: [EIP health checking in egoscale](https://app.clubhouse.io/exoscale/story/1953)

ip addresses: Add the Healthcheck parameters

---

.travis.yml
go.mod
go.sum
uuid.go

The satori/go.uuid package has critical
bugs (https://github.com/satori/go.uuid/issues/73).
This commit replaces this package by the gofrs/uuid fork.
In that package, The `Equal` function for UUID has been deleted (we
can use `==` directly for comparisons as explained in the `3.0.0`
release note of the package:
https://github.com/gofrs/uuid/releases/tag/v3.0.0).
Related to https://github.com/containous/traefik/pull/4718

Replace satori/go.uuid by gofrs/uuid

---

CHANGELOG.md
client.go
dns.go
request.go
runstatus.go

This change makes the "User-Agent" HTTP request header more informative,
and exposes it outside of the package if a caller wants to prefix it
with is own UA segment:
```go
import "github.com/exoscale/egoscale"
...
egoscale.UserAgent = fmt.Sprintf("Exoscale-CLI/%s %s", version, egoscale.UserAgent)
```

Improve the requests User-Agent HTTP header

---

addresses.go

Elastic IPs now have a description.
The description can be added when the EIP is created, or with an
update.
the list call will also return the description if it exists.

IP adresses: add description

---

affinity_groups.go
affinitygroups_response.go
antiaffinity_groups.go
antiaffinity_groups_response.go
generate/main.go

The Exoscale API now exposes dedicated Anti-Affinity Group calls for managing Anti-Affinity Groups in addition to Affinity Groups: add support for those new calls in egoscale.
Tested on my side

Add anti-affinity create group call

---

.travis.yml
networks.go
request_test.go

This change fixes the code testing that a client request times out when
configured with a deadline-type context.
Fixes #421.

tests: fix request client timeout handling

---

addresses.go
isos.go
networks.go
snapshots.go
templates.go
virtual_machines.go
volumes.go

This change annotates the API documentation regarding the use of tags parameter, so that users know that multiple tags are OR'ed and not AND'ed.
Story: [Allow listing VM with a AND for tags](https://app.clubhouse.io/exoscale/story/8665/allow-listing-vm-with-a-and-for-tags)

Annotate API doc regarding use of tags

---

internal/v2/security.go

http.Request offers GetBody() to provide a body copy,
but it is not available by the time we get to the signature
process in some contexts

signature: copy body when read

---

templates.go

This changes makes the `Displaytext` property of the
`RegisterCustomTemplate` optional.

RegisterCustomTemplate: Displaytext is optional

---

internal/v2/async.go
internal/v2/async_test.go
internal/v2/v2.gen.go
loadbalancer.go

This change updates the internal API V2 asynchronous operations handling
following the renaming of the "result" resource into "operation".

Update API V2 async operation code

---

loadbalancer.go

This changes fixes a bug in the `ListNetworkLoadBalancers()` call that
didn't set the embedded client/zone fields and lead to a nil pointer
derefencing when calling methods on a `NetworkLoadBalancerService`
object.

Fix a bug in the ListNetworkLoadBalancers call

---

volumes.go

This change fixes the `ListVolumes` to allow volumes search by ID.

Fix ListVolumes call to allow search by ID

---

virtual_machines.go

This changes introduces a new `ManagerID` filtering parameter to the
`ListVirtualMachines` call, enabling users to list the Compute instances
belonging to a specific Instance Pool.

ListVirtualMachines: add new parameter ManagerID

---

client.go
client_test.go
error.go

This change improves the error messages returned by the `GetWithContext`
method in case no resource or multiple resources are found, as it was
previously returned an error suggesting an API-side issue.

Improve GetWithContext() error messages.

---

sos_buckets_usage.go

This change replaces the type for `BucketUsage.Usage` to `int64`.

BucketUsage: change Usage to int64

---

sks.go
sks_test.go

- Change `SKSCluster.RequestKubeconfig()` to accept a context.Context
as parameter
- `SKSCluster.AddNodepool()` does not accept Kubernetes version as
user input

sks: fix various bugs

---

client.go
client_test.go
error.go
loadbalancer.go
sks.go

This change introduces a custom `v2.HttpRequestDoer` interface
implementation wrapping the client's `http.Client`, allowing us to
extract relevant error messages from API responses and report them to
the caller.

Improve API v2 errors handling

---

instance_pool.go

This change makes the `CreateInstancePool.AntiAffinityGroupIDs` field
optional.

Fix CreateInstancePool.AntiAffinityGroupIDs field

---

client.go
client_test.go

This change evolves the `NewClient()` function to accept 
options enabling the caller to override some properties during client
instantiation rather than after it's returned, as the internal API v2
client's properties are set during the client initialization and cannot
be changed afterwards.

Add Client options to NewClient()

---

loadbalancer.go

This change fixes a bug where the client would always send an empty
`tls_sni` value to the API when creating/updating a NLB service
healthcheck in HTTPS mode.

Fix NLB service healthcheck TLS SNI bug

---

zones.go
zones_test.go

This changes implements the public API v2 `list-zones` operation.

Add API v2 ListZones() call

---

internal/v2/sks_nodepool.go
internal/v2/sks_nodepool_test.go
internal/v2/v2.gen.go
sks.go
sks_test.go

* Update API v2 generated code
* SKS: rename `SKSCluster.Level` into `SKSCluster.ServiceLevel`
* SKS: add Anti-Affinity Groups support to SKS Nodepools

SKS: add Anti-Affinity Groups support to Nodepools 

---

client.go
client_test.go
go.mod
go.sum
networks_test.go
request_test.go
runstatus_incident_test.go
runstatus_maintenance_test.go
runstatus_page_test.go
runstatus_service_test.go
security_groups_test.go
v2/api/middleware.go
v2/client.go
version.go
volumes_test.go
zones_test.go

This change removes the http.Client deep-copying performed during the
embedded `v2.Client` initialization in `egoscale.NewClient()`, as it
didn't work properly with middleware (`http.Transport`) containing
unexported fields. Instead, we document the fact that the `http.Client`
passed via `v2.ClientOptWithHTTPClient()` could be altered and the
caller should then pass a copy of it if they don't want it changed
without their permission.
Also, this change refactors the `egoscale` package tests client
initialization disabling `v2.Client` embedding to avoid side-effects.

Fix embedded v2.Client initialization

---

v2/anti_affinity_group.go
v2/anti_affinity_group_test.go

This change introduces support for Anti-Affinity Group resources
management via the Exoscale V2 API.

v2: add support for Anti-Affinity Groups management

---

v2/instance_pool.go

This change fixes a crash caused by the dereferencing of a nil pointer
in case an Instance Pool doesn't have a manager.

v2: fix InstancePool.ManagerID resolution

---

v2/internal/public-api/public-api.gen.go
v2/sks.go
v2/sks_test.go

This change adds a new `AuthorityCert()` method to the `SKSCluster`
struct.

SKS: add SKSCluster.AuthorityCert() method

---

v2/sks.go
v2/sks_test.go

This change adds a new `RotateCCMCredentials()` method to the
`SKSCluster` struct.

SKS: add SKSCluster.RotateCCMCredentials()

---

v2/sks.go
v2/sks_test.go

This change makes the `SKSCluster.RotateCCMCredentials()` method
implementation wait for the API response before returning to the caller.

v2: make SKSCluster.RotateCCMCredentials() synchronous

---

.gitignore
v2/client.go
v2/client_test.go

This change introduces new `v2.Client` property setters allowing users
to override properties of a client at runtime.

v2: add client property setters

---

v2/instance_pool.go

This change adds support for `InstancePool.IPv6Enabled` field resetting.

v2: support InstancePool.IPv6Enabled field reset

---

client.go
v2/client.go
v2/client_test.go
version.go
version/version.go

This change moves the egoscale version from `version.go` to a dedicated
`version` package that can be used by both the root package and the `v2`
package.
This change introduces a new default HTTP client transport to the
`v2.Client`, which sets a custom HTTP request `User-Agent` header.

Relocating version + default HTTP v2 client transport 

---

v2/instance.go
v2/instance_test.go

This change replaces the `Instance.ManagerID` field with a more complete
dedicated `InstanceManager` type also containing the manager type.

v2: expose Instance manger via dedicated type

---

v2/instance_type.go
v2/instance_type_test.go

This change adds support for Compute instance types via the new type
`InstanceType`.

v2: add new InstanceType type

---

v2/anti_affinity_group.go
v2/anti_affinity_group_test.go
v2/api/error.go
v2/deploy_target.go
v2/deploy_target_test.go
v2/elastic_ip.go
v2/elastic_ip_test.go
v2/instance.go
v2/instance_pool.go
v2/instance_pool_test.go
v2/instance_test.go
v2/network_load_balancer.go
v2/network_load_balancer_test.go
v2/private_network.go
v2/private_network_test.go
v2/security_group.go
v2/security_group_test.go
v2/sks.go
v2/sks_test.go

This change introduces new `v2.Client.Find*()` convenience methods for
projects using egoscale and allowing users to specify API resource by
name or ID.

v2: add Client.Find*() methods

---

v2/instance_type.go
v2/instance_type_test.go

This change adds a new `v2.Client.FindInstanceType()` method.

v2: add Client.FindInstanceType() method

---

v2/anti_affinity_group.go
v2/elastic_ip.go
v2/elastic_ip_test.go
v2/instance_pool.go
v2/network_load_balancer.go
v2/private_network.go
v2/security_group.go
v2/sks.go

This change fixes how the v2 package sets optional API resource fields,
only including those if they actually hold a non-empty value.

v2: fix optional fields management

---

security_groups.go

Follow-up to 55d713e35cccb11e4c60e81e7de065466730700f, this change
modifies the type used for `AuthorizeSecurityGroupIngress.Icmp(Code|Type)`
to `int` to support -1 value.

Change AuthorizeSecurityGroupIngress.Icmp(Code|Type) type

---

v2/database.go
v2/database_test.go
v2/internal/public-api/dbaas_service.go
v2/internal/public-api/dbaas_service_test.go

This change replaces `v2.Database*` struct fields types with pointers to
allow a better detection of optional field values.

v2: use pointers in Database* structs

---

v2/instance.go
v2/instance_pool.go
v2/network_load_balancer.go
v2/sks.go

This change prevents from returning pointers to empty maps or slices
that can be returned by the API.

v2: don't return pointers to empty maps/slices

---

v2/private_network.go
v2/private_network_test.go

This change adds support for managed Private Networks leases
(`PrivateNetwork.Leases`).

v2: add support for Private Networks leases

---

v2/network_load_balancer.go

This change fixes a crashing bug in the
`NetworkLoadBalancer.AddService()` method.

v2: fix crash in NetworkLoadBalancer.AddService()

---

.github/workflows/main.yml
.gitmodules
Makefile
v2/template.go
v2/template_test.go

This change adds a new `Client.RegisterTemplate()` method.

v2: add new Client.RegisterTemplate() method

---

v2/database.go
v2/database_test.go
v2/internal/public-api/public-api.gen.go
v2/internal/public-api/sks_nodepool.go
v2/internal/public-api/sks_nodepool_test.go
v2/sks.go
v2/sks_test.go

This change adds a new `PrivateNetworkIDs` field to the `SKSNodepool`
resource struct.

v2: add support for Private Networks to SKS Nodepools 

---

v2/deploy_target.go
v2/instance.go
v2/instance_type.go

This change introduces a new `ToAPIMock()` method to resources
`DeployTarget`, `InstanceType` and `Instance`.

v2: add resource API mocks

---

v2/ssh_key.go
v2/ssh_key_test.go

This change introduces support for SSH keys resources
management via the Exoscale V2 API.

v2: add support for SSH keys management

---

v2/ssh_key.go
v2/ssh_key_test.go

This change fixes a bug in the `client.RegisterSSHKey()` method causing
it to return a polling-related error, where there is actually no need
for polling for this operation.

v2: fix RegisterSSHKey() method

---

v2/anti_affinity_group.go
v2/anti_affinity_group_test.go
v2/client_test.go
v2/database.go
v2/database_test.go
v2/deploy_target.go
v2/deploy_target_test.go
v2/elastic_ip.go
v2/elastic_ip_test.go
v2/instance.go
v2/instance_pool.go
v2/instance_pool_test.go
v2/instance_test.go
v2/instance_type.go
v2/network_load_balancer.go
v2/network_load_balancer_test.go
v2/private_network.go
v2/private_network_test.go
v2/quota.go
v2/quota_test.go
v2/security_group.go
v2/security_group_test.go
v2/sks.go
v2/sks_test.go
v2/snapshot.go
v2/snapshot_test.go
v2/ssh_key.go
v2/ssh_key_test.go
v2/template.go
v2/template_test.go

This change overhauls the `v2` package API in a major way, relocating
the resource methods on the `v2.Client` (e.g. `Instance.Start()` ->
`Client.StartInstance()`) in order to allow mocking the client using
interfaces easily.
This change introduces support for organization quotas management via
the Exoscale V2 API.

v2: API overhaul + quotas support

---

v2/internal/public-api/public-api.gen.go
v2/internal/public-api/snapshot.go
v2/internal/public-api/snapshot_test.go
v2/snapshot.go
v2/snapshot_test.go

This change introduces the missing `Snapshot.Size` struct field.

v2: add Snapshot.Size field

---

v2/database.go
v2/database_test.go

This change introduces a new method `GetDatabaseCACertificate()`
allowing users to retrieve the CA certificate to be used to access
Database Service using a TLS connection.

v2: add method Client.GetDatabaseCACertificate()

---

v2/database.go
v2/database_test.go

This change introduces a new `DatabaseServiceComponent` struct as well
as a new `DatabaseService.Components` field.

v2: add DatabaseServiceComponent struct

---

v2/sks.go
v2/sks_test.go

This change adds a new `Client.UpgradeSKSClusterServiceLevel()` method.

v2: add UpgradeSKSClusterServiceLevel() method

---

v2/security_group.go

This change fixes a bug in the `Client.CreateSecurityGroupRule()`
method, where a crash would occur when creating a rule without a
start/end port (e.g. ICMP rules).

v2: fix CreateSecurityGroupRule() method

---

v2/anti_affinity_group.go
v2/anti_affinity_group_test.go

This change adds a new `InstanceIDs` field to the `AntiAffinityGroup`
resource.

v2: add "AntiAffinityGroup.InstanceIDs" field

---

v2/database.go
v2/database_test.go
v2/elastic_ip.go
v2/instance_pool.go
v2/network_load_balancer.go
v2/oapi/oapi.gen.go
v2/oapi/oapi.go
v2/oapi/oapi_test.go
v2/private_network.go
v2/sks.go
v2/template.go

This change updates the `DatabaseServiceType` struct following public
API changes, where the `latest-version` field has been replaced with a
`available-versions` field.
This change updates structs that contain *nilable* strings properties
following a recent change in the public API, which no longer accepts
empty strings from clients.

v2: public API related changes

---

v2/instance.go
v2/instance_test.go

This change introduces a new `ListInstancesOpt` type to pass options to
the `Client.ListInstances()` method.

v2: add ListInstancesOpt options

---

v2/iam_access_key.go
v2/iam_access_key_test.go

This change adds support for resource-level IAM access key restrictions
via the `CreateIAMAccessKeyWithResources()` config function.

v2: add support for IAM access key resources

---

v2/oapi/oapi.gen.go
v2/sks_cluster.go
v2/sks_cluster_test.go

This change updates the `SKSClusterOIDCConfig` struct field
`RequiredClaim` to use a `map[string]string` type instead of a string.

v2: update SKSClusterOIDCConfig struct

---

v2/sks_cluster.go
v2/utils.go

Returns an array of structures like that:
```
type SKSClusterDeprecatedResource struct {
Group          *string
RemovedRelease *string
Resource       *string
SubResource    *string
Version        *string
RawProperties  map[string]string
}
```
Example data:
```
{
"Group": "policy",
"RemovedRelease": "1.25",
"Resource": "podsecuritypolicies",
"SubResource": "",
"Version": "v1beta1",
"RawProperties": {
"group": "policy",
"removed_release": "1.25",
"resource": "podsecuritypolicies",
"subresource": "",
"version": "v1beta1"
}
}
```

Add an helper function to list sks cluster deprecated resources

---

.github/workflows/main.yml
.golangci.yml
v2/instance_pool.go

Add a helper method to wait for convergence of an instance pool (e.g. after creating or scaling it).

Wait for instance pool size convergence

---

.golangci.yml
v2/client_mock.go
v2/dns.go
v2/dns_test.go

This PR allows management of DNS with egoscale v2, as available in Public API:
https://openapi-v2.exoscale.com/#endpoint-dns

v2: DNS resources from Public API

---

v2/client.go

This PR prevents endpoint override if endpoint is IP address. This means `environment` and `zone` will be ignored in the case of IP address.
Motivation for this PR is to allow running a mock public API server using [httptest](https://pkg.go.dev/net/http/httptest@go1.19).
Relevant tests:
```
$ go test ./... -count=1 -run TestSetEndpointFromContext 
ok      github.com/exoscale/egoscale    0.003s [no tests to run]
?       github.com/exoscale/egoscale/admin      [no test files]
?       github.com/exoscale/egoscale/generate   [no test files]
ok      github.com/exoscale/egoscale/v2 0.003s
ok      github.com/exoscale/egoscale/v2/api     0.002s [no tests to run]
ok      github.com/exoscale/egoscale/v2/oapi    0.003s [no tests to run]
?       github.com/exoscale/egoscale/version    [no test files …
```

v2: don't overwrite Host header if host is IP address

---

.github/workflows/main.yml
client.go
dns.go
go.mod
go.sum
request.go
runstatus.go
v2/api/middleware.go
v2/api/middleware_test.go
v2/api/security.go
v2/client.go
v2/client_test.go
virtual_machines.go

This PR changes default v2 HTTP client to [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp).
This new library provides retry logic for HTTP server errors and network errors.
Debug logs for retries can be seen when running unit tests:
```
=== RUN   TestDefaultClient_Retry                                                                                      
2022/09/05 14:03:38 [DEBUG] GET http://127.0.0.1:42175                                                                 
2022/09/05 14:03:38 [DEBUG] GET http://127.0.0.1:42175 (status: 500): retrying in 1s (4 left)                          
2022/09/05 14:03:39 [DEBUG] GET http://127.0.0.1:42175 (status: 500): retrying in 2s (3 left)                          
--- PASS: TestDefaultClient_Retry (3.00s)
```
Because user-agent …

v2: use hashicorp/go-retryablehttp as default http client

---

v2/client.go

This PR prevents `go-retryablehttp` client from writing debug logs to stderr.

v2: silence go-retryablehttp client

---

v2/client_mock.go
v2/database_mysql.go
v2/database_mysql_test.go
v2/database_pg.go
v2/database_pg_test.go
v2/database_redis.go
v2/database_redis_test.go

Implements database migration stop calls for databases supporting it: Redis, PostgreSQL, MySQL.

v2: add database migration stop

---

.github/workflows/main.yml
.golangci.yml
admin/doc.go
doc.go
isos.go
request_test.go
templates.go
v2/client.go
v2/deploy_target.go
v2/deploy_target_test.go
v2/instance.go
v2/instance_pool.go
v2/instance_pool_test.go
v2/instance_test.go
v2/oapi/oapi.gen.go
v2/sks_nodepool.go
v2/sks_nodepool_test.go
virtual_machines.go

We regenerate the wrappers for the latest OpenAPI spec and add an option to the ListInstances call that allows users to filter by IP address.

ListInstances: accept filter by IP option

---

v2/security_group.go

`FindSecurityGroups` is intended to allow passing in filters to the `list-security-groups` OpenAPI command. The underlying OpenAPI param structure is passed through directly to the command, no other change from `ListSecurityGroups`

security_group: support FindSecurityGroups to allow param passing

---

CHANGELOG.md
v2/security_group_rule.go
version/version.go

Rules should have a simple discriminant to understand when a public security group is being referred to

sg-rule: support public security groups when listing

---

v3/client.go
v3/clientopts.go
v3/logger.go
v3/zoned_client.go

Example usage of `ForEachZone` and logging  with builtin `Logger` implementation (`StandardLogger`):
```go
func main() {
client, err := exoscale.DefaultClient(
exoscale.ClientOptWithCredentialsFromEnv(),
exoscale.ClientOptWithLogger(exoscale.NewStandardLogger(os.Stdout, true)),
)
if err != nil {
panic(err)
}
client.ForEachZone(func(c *exoscale.Client, zone oapi.ZoneName) {
l, err := c.Compute().LoadBalancers().Get(context.Background(), <id>)
if err != nil {
fmt.Println(err)
} else {
fmt.Println(l)
}
})
}
```

v3: ForEachZone helper and logging

---

CHANGELOG.md
v2/iam.go
v2/iam_org_policy.go
v2/iam_org_policy_test.go
v2/iam_role.go
v2/iam_role_test.go

Makes IAMv3 Policy Resources field noop. More details in the attached story.

Make IAMv3 policy Resources field NOOP

---

CHANGELOG.md
v2/client.go

This PR fixes #573 .
As stated in the issue, `SetHTTPClient` did not actually replace the HTTP client used by underlying `oapi` client.

Fix SetHTTPClient (v2)

---

CHANGELOG.md
v2/iam_role.go

Fixes the bug with iam role labels where API returns no labels field (equivalent to nil) but egoscale translates it to empty slice.

v2: fix issue with iam role labels

---

v3/client.go
v3/generator/client/client.go
v3/generator/client/client.tmpl
v3/generator/operations/request.tmpl
v3/generator/schemas/schemas.go
v3/operations.go
v3/schemas.go

Use the new API ListZones to replace the zone endpoint static mapping.
Renaming of `URL` to `Endpoint` to match the API definition 
Generator support Extension attribute with `x-go-type`
V3 Alpha development

V3: New API ListZones Endpoint Mapping

---

CHANGELOG.md
Makefile

Due to the introduction of `.ONESHELL` to `Makefile` in #618  the shell commands in each target are now executed in one shell session. This improves performance but also means that changing the directory in one line also changes the directory for the following lines(doesn't happen across targets). Unfortunately it broke the targets `oapigen` and `generate`.

Makefile: fix targets

---

CHANGELOG.md
v3/api.go
v3/generator/operations/operations.go
v3/generator/operations/request.tmpl
v3/operations.go
v3/schemas.go

To identify which API operations a given call executes we print the operation ID in addition to the request dump when tracing is enabled. For a CLI command the output will look like this:
```shell
❯ EXOSCALE_TRACE=1 exo compute -z ch-gva-2 bs list
>>> Operation: list-zones
GET /v2/zone HTTP/1.1
Host: api-ch-gva-2.exoscale.com
...
>>> Operation: list-block-storage-volumes
GET /v2/block-storage HTTP/1.1
Host: api-ch-gva-2.exoscale.com
```

v3 trace: print operation IDs

---

go.mod

Fixes #586
After the merge of this PR, you should create a tag `v1.19.1` as explained [here](https://go.dev/ref/mod#go-mod-file-retract).
> To retract a version, a module author should add a retract directive to `go.mod`, then publish a new version containing that directive. **The new version must be higher than other release or pre-release versions**; that is, the `@latest` [version query](https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered.
Related to https://github.com/exoscale/egoscale/issues/482
Related to https://github.com/exoscale/egoscale/issues/483

fix: incomplete package retraction

---

CHANGELOG.md
v3/metadata/metadata.go

Metadata package to interact with exoscale metadata server from an exoscale Instance
test from Instance
```Golang
package main
import (
"context"
"fmt"
"log"
"github.com/exoscale/egoscale/v3/metadata"
)
func main() {
endpoints := []metadata.Endpoint{
metadata.AvailabilityZone,
metadata.CloudIdentifier,
metadata.InstanceID,
metadata.LocalHostname,
metadata.LocalIpv4,
metadata.PublicHostname,
metadata.PublicIpv4,
metadata.ServiceOffering,
metadata.VMID,
}
for _, endpoint := range endpoints {
resp, err := metadata.Get(context.Background(), endpoint)
if err != nil {
log.Fatal(err)
}
fmt.Printf("Response for %s: %s\n", endpoint, resp)
}
resp, err := metadata.UserData(context.Background())
if err != nil {
log.Fatal(err)
}
fmt.Printf("Response for user-data: %s\n", …
```

v3: Add a metadata package to interact with

---

CHANGELOG.md
README.md
go.mod
v3/README.md

After merging this change and pushing the release tag `v3.0.0`, users will see the following when opening `https://pkg.go.dev/github.com/exoscale/egoscale@v3.0.0` <- (note that the v3 suffix is missing, thus they will be redirected to v3)
If users open `https://pkg.go.dev/github.com/exoscale/egoscale` they will not be automatically redirected, but they will see:
This was tested on [a fork](https://pkg.go.dev/github.com/sauterp/egoscale).

deprecate v1 and v2 and remove alpha notice for v3

---

.github/workflows/generate_v3.yaml
.gitignore
CHANGELOG.md
Makefile
v3/generator/source.yaml
v3/schemas.go

Everyday at 7 AM we trigger a GitHub Action that runs `make generate`. This will download the exoscale API spec and try to regenerate egoscale v3. If there are changes, we create a PR with those changes.
NOTE: the latest run of the action fails, because I changed the base to `master` which means there's a conflict, because source.yaml is ignored in `master`. [example](https://github.com/exoscale/egoscale/actions/runs/9955412776/job/27503113843?pr=643#step:4:108)
Once this PR is merged the problem will disappear. See testing below for tests on a previous commit.
Pushing this PR automatically [generated this PR](https://github.com/exoscale/egoscale/pull/644)

v3: automate regeneration when spec changes

---

.github/workflows/build-public-tooling.yaml
CHANGELOG.md

Whenever new commits are pushed this action tries to build the cli, CSI and tf provider with the new change. The build usually needs under a minute and all three run in parallel. This check will help to prevent us from doing backwards incompatible changes by accident.
The CSI build will pass once this PR is merged: https://github.com/exoscale/exoscale-csi-driver/pull/35

v3: github action to build tooling with new commit

---

.github/workflows/build-public-tooling.yaml
.github/workflows/generate_v3.yaml
CHANGELOG.md

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Also allow manually triggering the PR and enable the public tooling build on the automatically created PR.
The generated [PR](https://github.com/exoscale/egoscale/pull/648) appeared

generate_v3: replace deprecated ::set-output

---

CHANGELOG.md
Makefile
request_test.go
v3/generator/helpers/helpers.go
v3/generator/helpers/helpers_test.go

Generator would break with the [new DBaaS enums for Datadog](https://github.com/exoscale/dbaas-api/blob/40b1ba53298095740a736f55905f3e4aff62a542/modules/dbaas-schemas/resources/schemas/dbaas-api.edn#L2562)
```clojure
:enum-datadog-site
#{"us3.datadoghq.com"
"ddog-gov.com"
"datadoghq.eu"
"us5.datadoghq.com"
"ap1.datadoghq.com"
"datadoghq.com"}
```
For the entry "ddog-gov.com" the existing code considers only one separator and it generates 
```go
EnumDatadogSiteDdogGov.com      EnumDatadogSite = "ddog-gov.com"
```
With these changes it would generate 
```go
EnumDatadogSiteDdogGovCom      EnumDatadogSite = "ddog-gov.com"
```

handling multiple separators

---

v3/client.go
v3/generator/client/client.tmpl

- deprecate `WithHttpClient`
- add `WithHTTPClient`
Use the same initialism as `ClientOptWithHTTPClient`.

v3: fix WithHttpClient name

---

CHANGELOG.md
v3/api.go

Code generated by egoscale for FindInstanceType only allows finding by `id`. We allow users to specify a string of the form `{{InstanceType.Family}}.{{InstanceType.Size}}` for instance types; as this is a unique case, rather that complexify the rendering template, we add a small different helper that allows for this.
Already exists in `terraform-provider-exoscale` as a [helper](https://github.com/exoscale/terraform-provider-exoscale/blob/ffc19c87f1b7f3d2e1a590d553f8ac9c7119aa96/pkg/utils/utils.go#L278), which should be removed

v3: helper for finding instance types

---

CHANGELOG.md
v3/generator/operations/operations.go
v3/operations.go

`QueryParams` and its template vas missing a `FieldName` to differentiate between the name of the field in the golang struct and the actual json query

generator v3: correctly build parameter keys for queries
